import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Put your name here
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        String title = "No title available";
        String link = "No link available";
        String desc = "No description available";

        if (channel.child(getChildElement(channel, "title"))
                .numberOfChildren() > 0) {
            title = channel.child(getChildElement(channel, "title")).child(0)
                    .label();
        }

        if (channel.child(getChildElement(channel, "link"))
                .numberOfChildren() > 0) {
            link = channel.child(getChildElement(channel, "link")).child(0)
                    .label();
        }

        if (channel.child(getChildElement(channel, "description"))
                .numberOfChildren() > 0) {
            desc = channel.child(getChildElement(channel, "description"))
                    .child(0).label();
        }
        out.println("<html>\n<head>\n<title>" + title
                + "</title>\n</head>\n<body>\n <h1><a href=\"" + link + "\">"
                + title + "</a></h1>\n <p>" + desc
                + " </p>\n <table border=\"1\">\n"
                + "  <tr>\n   <th>Date</th>\n   <th>Source</th>\n "
                + "<th>News</th>\n  </tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     *
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>\n</body>\n</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int numChildren = xml.numberOfChildren();
        int location = -1;
        int i = 0;

        while (i < numChildren) {
            if (xml.child(i).label().equals(tag)) {
                location = i;
                return location;
            }
            i++;
        }

        return location;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        String pubDate = "No pub date available";
        String source = "No source available";
        String news = "No news available";

        if (getChildElement(item, "pubDate") >= 0
                && item.child(getChildElement(item, "pubDate"))
                        .numberOfChildren() > 0) {
            pubDate = item.child(getChildElement(item, "pubDate")).child(0)
                    .label();
        }

        if (getChildElement(item, "source") >= 0
                && item.child(getChildElement(item, "source"))
                        .numberOfChildren() > 0) {
            source = item.child(getChildElement(item, "source")).child(0)
                    .label();
        }

        if (getChildElement(item, "title") >= 0 && item
                .child(getChildElement(item, "title")).numberOfChildren() > 0) {
            news = item.child(getChildElement(item, "title")).child(0).label();
        }

        out.println("  <tr>\n   <td>" + pubDate + "</td>");
        out.println("   <td><a href=\"");

        if (getChildElement(item, "source") >= 0
                && item.child(getChildElement(item, "source"))
                        .numberOfChildren() > 0) {
            out.println(item.child(getChildElement(item, "source"))
                    .attributeValue("url"));
        }

        out.println("\">" + source + "</a></td>");
        out.println("   <td><a href=\"");

        if (getChildElement(item, "title") >= 0 && item
                .child(getChildElement(item, "title")).numberOfChildren() > 0) {
            out.println(
                    item.child(getChildElement(item, "link")).child(0).label());
        }

        out.println("\">" + news + "</a></td>\n  </tr>");

    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        XMLTree rss = new XMLTree1(file);
        XMLTree channel = rss.child(0);
        int i = getChildElement(channel, "item");

        SimpleWriter out1 = new SimpleWriter1L(url);

        if (rss.label().equals("rss") && rss.hasAttribute("version")
                && rss.attributeValue("version").equals("2.0")) {
            outputHeader(channel, out1);

            while (i < channel.numberOfChildren()) {
                processItem(channel.child(i), out1);
                i++;
            }
            outputFooter(out1);
        }
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.println("Enter RSS 2.0 URL: ");
        XMLTree rss = new XMLTree1(in.nextLine());

        out.println("Enter a file name: ");
        String fileName = in.nextLine();
        int i = 0;

        SimpleWriter out1 = new SimpleWriter1L(fileName + ".html");

        out1.println("<html>\n <head>\n  <title>Top Stories</title>\n </head>");
        out1.println(" <body>\n  <h2>Top Stories</h2>\n   <ul>");

        while (i < rss.numberOfChildren()) {
            String link = rss.child(i).attributeValue("url");
            String html = rss.child(i).attributeValue("file");
            String name = rss.child(i).attributeValue("name");
            out1.println("    <li>\n     <a href=\"");
            out1.println(html + "\">" + name + "</a>");
            processFeed(html, link, out1);
            out1.println("    </li>");
            i++;
        }

        out1.println("   </ul>\n </body>\n</html>");

        in.close();
        out.close();
        out1.close();
    }

}
